# --- Main Prompt Structure ---
# Defines the order, layout, and connecting arrows for all modules.
format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#326ce5)\
$docker_context\
$kubernetes\
[](fg:#326ce5 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$cmd_duration\
$jobs\
[](fg:#212736 bg:#1d2230)\
$battery\
$time\
[ ](fg:#1d2230)\
\n$character"""

# --- OS Indicator ---
[os]
format = '$symbol'
disabled = false
[os.symbols]
Windows = " "
Ubuntu = ""
Raspbian = ""
NixOS = ""
Mint = ""
Manjaro = " "
Macos = ""
Linux = ""
Gentoo = ""
Fedora = ""
Debian = ""
CentOS = ""
Arch = ""
Alpine = ""

# --- Directory ---
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# --- Git ---
[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

# --- Developer Context (Docker & Kubernetes) ---
# This block uses a distinct blue background and will only show when a context is active.
[docker_context]
symbol = " "
style = "fg:#ffffff bg:#326ce5"
format = '[[ $symbol$context ](fg:#ffffff bg:#326ce5)]($style)'

[kubernetes]
symbol = "󱃾 "
style = "fg:#ffffff bg:#326ce5"
format = '[[ $symbol$context( ☸ $namespace) ](fg:#ffffff bg:#326ce5)]($style)'
disabled = false

# --- Language & Command Context ---
# This block shows language versions, command duration, and background job status.
[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[cmd_duration]
min_time = 2000  # Only show if command takes longer than 2 seconds
style = "bg:#212736"
format = '[[ 󰔟 $duration ](fg:#769ff0 bg:#212736)]($style)'

[jobs]
symbol = ""
style = "bg:#212736"
number_threshold = 1
format = '[[ $symbol$number ](fg:#769ff0 bg:#212736)]($style)'

# --- System Status (Battery & Time) ---
# This block shows laptop battery and the current time.
[battery]
full_symbol = ""
charging_symbol = "󰂄"
discharging_symbol = ""
unknown_symbol = "?"
empty_symbol = ""
disabled = false
# Color-coded display based on charge level
[[battery.display]]
threshold = 20
style = "fg:#f14c4c" # Red
[[battery.display]]
threshold = 50
style = "fg:#f5a70a" # Yellow
[[battery.display]]
style = "fg:#a0a9cb" # Default light blue/lavender

[time]
disabled = false
time_format = "%I:%M %p"
style = "bg:#1d2230"
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)' # Icon removed to allow battery symbol to lead

# --- Prompt Character ---
# Displays a different symbol for success and failure.
[character]
success_symbol = "[❯](fg:#a3aed2)"
error_symbol = "[✗](fg:#e06c75)"
vimcmd_symbol = "[](fg:green)"
